const int COLOR_REGISTER_LENGTH = 18;

#include <raylib.h>

Color country_color(int i) {
	if(i < 0 || i > COLOR_REGISTER_LENGTH) return BLANK;
	Color COLOR_REGISTER[18] = { YELLOW, GOLD, ORANGE, PINK, RED, MAROON, GREEN, LIME, DARKGREEN, SKYBLUE, BLUE, DARKBLUE, PURPLE, VIOLET, DARKPURPLE, BEIGE, BROWN, DARKBROWN };
	return COLOR_REGISTER[i];
}

